# This file was generated by GoReleaser. DO NOT EDIT.
class Urlsplit < Formula
  desc ""
  homepage ""
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/relvacode/urlsplit/releases/download/0.1/urlsplit_0.1_osx_x86_64.tar.gz"
    sha256 "10a6d8b4a6c940029951de2e89e77e09c44570772e4cd918fc478e4eeed0a3c9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/relvacode/urlsplit/releases/download/0.1/urlsplit_0.1_linux_x86_64.tar.gz"
      sha256 "6e991353eec81f0255b2aa86dcfbee92902abfc8e5de25a653f00d3a236bdcf7"
    end
  end

  def install
    bin.install "urlsplit"
  end
end
